// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRC22PNYYcJTC9oU_LJTodNjsNxDgHdwo',
    appId: '1:408715972861:web:bdd48531bf20ef7fe46e94',
    messagingSenderId: '408715972861',
    projectId: 'messenger-5360d',
    authDomain: 'messenger-5360d.firebaseapp.com',
    storageBucket: 'messenger-5360d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlkBA_0wOhxfGvZTV3X3XOaJEb3Qfcy2E',
    appId: '1:408715972861:android:aef447ba882bbf99e46e94',
    messagingSenderId: '408715972861',
    projectId: 'messenger-5360d',
    storageBucket: 'messenger-5360d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLtuyM53kODQW4rQpV8mIj9ADtwoDgALU',
    appId: '1:408715972861:ios:b2dbf615d19c2459e46e94',
    messagingSenderId: '408715972861',
    projectId: 'messenger-5360d',
    storageBucket: 'messenger-5360d.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLtuyM53kODQW4rQpV8mIj9ADtwoDgALU',
    appId: '1:408715972861:ios:8312e2288dcec369e46e94',
    messagingSenderId: '408715972861',
    projectId: 'messenger-5360d',
    storageBucket: 'messenger-5360d.appspot.com',
    iosBundleId: 'com.example.messenger.RunnerTests',
  );
}
